# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: node_js
node_js:
  - "node"
  - "8"
env:
  - COUCHDB_USER=james
  - COUCHDB_PASSWORD=grobblefruit
  - COUCHDB_PASS=grobblefruit


services:
  - couchdb

before_script:
  - curl -s -X PUT http://localhost:5984/_config/admins/james -d '"grobblefruit"'

notifications:
  email:
    on_success: change
    on_failure: change
