# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
dist: xenial

language: node_js

node_js:
  - "node"
  # - "8"

env:
  global:
    - COUCHDB_USER=james COUCHDB_PASSWORD=grobblefruit COUCHDB_PASS=grobblefruit

addons:
  apt:
    sources:
      - sourceline: 'deb https://apache.bintray.com/couchdb-deb xenial main'
        key_url: 'https://couchdb.apache.org/repo/bintray-pubkey.asc'
    packages:
      - couchdb


services:
  - couchdb


before_script:
  # need couchdb 2+
  # - echo "deb https://apache.bintray.com/couchdb-deb trusty main" \
  #   | sudo tee -a /etc/apt/sources.list
  # - curl -L https://couchdb.apache.org/repo/bintray-pubkey.asc \
  #   | sudo apt-key add -
  # - sudo apt-get update && sudo apt-get install couchdb
  # - sudo -i -u couchdb COUCHDB_USER=james COUCHDB_PASSWORD=grobblefruit /home/couchdb/bin/couchdb
  -  curl -s -X PUT http://localhost:5984/_config/admins/james -d '"grobblefruit"'

notifications:
  email:
    on_success: change
    on_failure: change
